function code = code_averaging(cfg)
% CODE_AVERAGING  Script for block B08_Averaging.
%
%   Coherent integration of n_avg sweeps. The deterministic echo is identical
%   in every sweep, so it survives the 1/N division unchanged; the noise is
%   independent from sweep to sweep and is therefore reduced by sqrt(N). The
%   total single-sweep noise level (thermal + quantisation) arrives on port 2
%   and is injected here at its post-integration level.
%
%   The previous version of this block summed n_avg copies of the input and
%   added a fresh noise sample to each copy, which divided the noise by N
%   instead of sqrt(N) and double-counted the signal. Integration gain is
%   sqrt(N) in amplitude, never N.
%
%   Ports: (in_signal, noise_std, n_avg) -> avg [n_tones x n_positions]

n_freq = cfg.n_tones;
n_pos  = cfg.n_positions;

code = sprintf([...
'function avg = fcn(in_signal, noise_std, n_avg)\n' ...
'%%#codegen\n' ...
'%% B08_Averaging: coherent integration of n_avg sweeps.\n' ...
'%% signal term: N/N = 1, noise term: sqrt(N)/N = 1/sqrt(N).\n' ...
'n_freq = %d; n_pos = %d;\n' ...
'n = floor(n_avg);\n' ...
'if n < 1, n = 1; end\n' ...
'sd = noise_std(:);            %% n_pos x 1, single-sweep noise\n' ...
'sd = sd/sqrt(n);              %% post-integration noise\n' ...
'm = repmat(sd.'', n_freq, 1);  %% n_freq x n_pos\n' ...
'n_r = randn(n_freq, n_pos).*m;\n' ...
'n_i = randn(n_freq, n_pos).*m;\n' ...
'avg = in_signal + complex(n_r, n_i);\n' ...
'end\n'], n_freq, n_pos);
end
