function code = code_tx(cfg)
% CODE_TX  Script for block B03_TX_Chain.
%
%   DAC -> predriver -> PA (soft compression at P1dB) -> TX cable.
%   Output is the *normalised* transmit waveform (peak amplitude 1); the
%   absolute radiated power is applied in B04_Channel through EIRP. Keeping
%   the two apart avoids the double scaling that the previous version had.
%
%   Ports: (tx_in, pa_gain_dB) -> tx_out [n_tones x 1]

n_freq       = cfg.n_tones;
predriver_dB = gpr_cfg_value(cfg, 'predriver_gain_dB', 22);
cable_dB     = gpr_cfg_value(cfg, 'tx_cable_loss_dB', 2);
p1dB_dBm     = gpr_cfg_value(cfg, 'pa_p1dB_dBm', 37);
r_load       = gpr_cfg_value(cfg, 'load_impedance', 50);

code = sprintf([...
'function tx_out = fcn(tx_in, pa_gain_dB)\n' ...
'%%#codegen\n' ...
'%% B03_TX_Chain: predriver + PA soft compression + cable loss, peak-normalised.\n' ...
'n_freq = %d;\n' ...
'r_load = %g;\n' ...
'predriver_lin = 10^(%g/20);\n' ...
'cable_lin = 10^(-%g/20);\n' ...
'p1dB_watts = 10^((%g-30)/10);\n' ...
'v_p1dB = sqrt(2*r_load*p1dB_watts);\n' ...
'if v_p1dB <= 0, v_p1dB = 1; end\n' ...
'pa_lin = 10^(pa_gain_dB/20);\n' ...
'drive = tx_in * (predriver_lin*pa_lin);\n' ...
'compressed = complex(zeros(n_freq, 1), zeros(n_freq, 1));\n' ...
'for k = 1:n_freq\n' ...
'    m = abs(drive(k))/v_p1dB;            %% normalised drive level\n' ...
'    c = 1/(1 + m^4)^(1/4);               %% soft limiter (4th-order roll-off)\n' ...
'    compressed(k) = drive(k)*c*cable_lin;\n' ...
'end\n' ...
'pk = 0;\n' ...
'for k = 1:n_freq\n' ...
'    a = abs(compressed(k));\n' ...
'    if a > pk, pk = a; end\n' ...
'end\n' ...
'if pk > 0\n' ...
'    tx_out = compressed/pk;\n' ...
'else\n' ...
'    tx_out = compressed;\n' ...
'end\n' ...
'end\n'], n_freq, r_load, predriver_dB, cable_dB, p1dB_dBm);
end
