function code = code_rx(cfg)
% CODE_RX  Script for block B06_RX.
%
%   RX antenna -> cable -> LNA, including the analog system response
%   (cable delay + passband ripple) that B09_Calibration divides back out.
%   Both blocks bake the SAME cfg values, so the calibration is exact; if you
%   change the response model here you must change code_calibration.m too.
%
%   The block also outputs the input-referred thermal noise standard
%   deviation, which B08_Averaging injects at its post-integration level.
%   Splitting "signal" and "noise level" this way is what makes the
%   integration gain correct: the previous version drew a fresh noise sample
%   per tone and position here AND again in the averaging block, so the noise
%   fell with N instead of sqrt(N).
%
%   Ports: (rx_in, lna_dB, nf_dB, tone_bw) -> [rx_out, noise_std]
%       rx_out    [n_tones x n_positions] complex
%       noise_std scalar, standard deviation of each quadrature component

rx_gain  = cfg.rx_antenna_gain_dBi;
cable_dB = gpr_cfg_value(cfg, 'rx_cable_loss_dB', 2);
bw_def   = gpr_cfg_value(cfg, 'tone_bandwidth', 20e3);
delay    = gpr_cfg_value(cfg, 'rx_cable_delay', 0);
ripple   = gpr_cfg_value(cfg, 'cal_ripple_depth', 0);
cycles   = gpr_cfg_value(cfg, 'cal_ripple_cycles', 0);
f0       = cfg.f_start;
f1       = cfg.f_stop;
n_freq   = cfg.n_tones;
n_pos    = cfg.n_positions;

code = sprintf([...
'function [rx_out, noise_std] = fcn(rx_in, lna_dB, nf_dB, tone_bw)\n' ...
'%%#codegen\n' ...
'%% B06_RX: antenna + cable + LNA + analog system response, and the noise level.\n' ...
'%% The system response is removed again by B09_Calibration (same constants).\n' ...
'n_freq = %d;\n' ...
'f_start = %g; f_stop = %g;\n' ...
'cable_delay = %g;\n' ...
'ripple_depth = %g;\n' ...
'ripple_cycles = %g;\n' ...
'kB = 1.380649e-23; T0 = 290;\n' ...
'rx_ant_lin = 10^(%g/20);\n' ...
'cable_lin = 10^(-%g/20);\n' ...
'bw_default = %g;\n' ...
'if tone_bw <= 0, tone_bw = bw_default; end\n' ...
'lna_lin = 10^(lna_dB/20);\n' ...
'g = lna_lin*cable_lin;\n' ...
'bw = f_stop - f_start;\n' ...
'if bw <= 0, bw = 1; end\n' ...
'if n_freq < 2, df = 0; else, df = bw/(n_freq-1); end\n' ...
'H_sys = complex(ones(n_freq, 1), zeros(n_freq, 1));\n' ...
'for k = 1:n_freq\n' ...
'    fk = f_start + (k-1)*df;\n' ...
'    H_sys(k) = exp(-1j*2*pi*fk*cable_delay) ...\n' ...
'             * (1 + ripple_depth*sin(2*pi*(fk - f_start)/bw*ripple_cycles));\n' ...
'end\n' ...
'rx_out = complex(zeros(n_freq, %d), zeros(n_freq, %d));\n' ...
'for k = 1:n_freq\n' ...
'    rx_out(k, :) = rx_in(k, :)*(H_sys(k)*g*rx_ant_lin);\n' ...
'end\n' ...
'nf_lin = 10^(nf_dB/10);\n' ...
'if nf_lin < 1, nf_lin = 1; end\n' ...
'noise_pwr = kB*T0*tone_bw*nf_lin;   %% W, referred to the receiver input\n' ...
'noise_std = sqrt(noise_pwr/2)*g;    %% per quadrature component, after gain\n' ...
'end\n'], n_freq, f0, f1, delay, ripple, cycles, rx_gain, cable_dB, bw_def, n_pos, n_pos);
end
