function code = code_report(cfg)
% CODE_REPORT  Script for block B14_Report.
%
%   Turns the detection matrix into the numbers an operator reads:
%       rep(1) = number of detected cells
%       rep(2) = number of distinct detections (8-connected clusters)
%       rep(3) = mean depth of the cluster peaks [m]
%       rep(4) = mean cross-range of the cluster peaks [m]
%       rep(5) = shallowest cluster peak [m]
%       rep(6) = deepest cluster peak [m]
%
%   Two corrections with respect to the previous version:
%
%   1. Cluster counting.  The old "a cell starts a new cluster if none of its
%      four already-scanned neighbours is set" rule is only exact for
%      4-connectivity.  For 8-connectivity it overcounts: the pattern
%      .X. / X.X is one component but produces two seeds, and on the mode-B
%      reference scene the block reported 29 clusters where there are 5.
%      This version runs a proper two-pass labelling with a union-find table.
%
%   2. Positions are taken at the peak of the migrated amplitude inside each
%      cluster, not at the pixel centroid.  A detection blob is not
%      symmetric - it carries the migration skirt of the target and, in a
%      crowded scene, part of a neighbour - so the centroid is biased by up
%      to a metre while the peak sits on the target.
%
%   Ports: (det, mig, f_start, f_stop, moisture, sigma, scan_len)
%          -> rep [6 x 1]

n_ifft   = cfg.n_ifft;
n_pos    = cfg.n_positions;
n_freq   = cfg.n_tones;
max_lab  = gpr_cfg_value(cfg, 'max_detections', 256);

code = sprintf([...
'function rep = fcn(det, mig, f_start, f_stop, moisture, sigma, scan_len)\n' ...
'%%#codegen\n' ...
'%% B14_Report: cluster the CFAR detections and summarise them.\n' ...
'n_ifft = %d; n_pos = %d; n_freq = %d; max_lab = %d;\n' ...
'c = 299792458;\n' ...
'if f_start <= 0, f_start = 1e6; end\n' ...
'if f_stop <= f_start, f_stop = f_start + 1e6; end\n' ...
'if moisture < 0, moisture = 0; end\n' ...
'if sigma <= 0, sigma = 1e-4; end\n' ...
'[~, ~, ~, ~, v_soil] = soil_permittivity((f_start + f_stop)/2, moisture, sigma);\n' ...
'if n_freq < 2, df = 1; else, df = (f_stop - f_start)/(n_freq - 1); end\n' ...
'if df <= 0, df = 1; end\n' ...
'dr = v_soil/(2*n_ifft*df);\n' ...
'if dr <= 0, dr = 1; end\n' ...
'if n_pos < 2, dx = scan_len; else, dx = scan_len/(n_pos - 1); end\n' ...
'img = abs(mig);\n' ...
'hits = det > 0;\n' ...
'%% ---- pass 1: provisional labels + union-find on the 8-neighbourhood ----\n' ...
'L = zeros(n_ifft, n_pos);\n' ...
'parent = zeros(1, max_lab);\n' ...
'nlab = 0;\n' ...
'for i = 1:n_ifft\n' ...
'    for j = 1:n_pos\n' ...
'        if ~hits(i, j), continue; end\n' ...
'        best = 0;\n' ...
'        if i > 1\n' ...
'            if j > 1 && L(i-1, j-1) > 0, [best, parent] = uf_union(best, L(i-1, j-1), parent); end\n' ...
'            if L(i-1, j) > 0, [best, parent] = uf_union(best, L(i-1, j), parent); end\n' ...
'            if j < n_pos && L(i-1, j+1) > 0, [best, parent] = uf_union(best, L(i-1, j+1), parent); end\n' ...
'        end\n' ...
'        if j > 1 && L(i, j-1) > 0, [best, parent] = uf_union(best, L(i, j-1), parent); end\n' ...
'        if best == 0\n' ...
'            if nlab < max_lab\n' ...
'                nlab = nlab + 1;\n' ...
'                parent(nlab) = nlab;\n' ...
'                best = nlab;\n' ...
'            else\n' ...
'                best = max_lab;      %% label table full: merge the overflow\n' ...
'            end\n' ...
'        end\n' ...
'        L(i, j) = best;\n' ...
'    end\n' ...
'end\n' ...
'%% ---- pass 2: resolve to roots and collect per-cluster statistics ----\n' ...
'cnt = zeros(1, max_lab); pk = -inf(1, max_lab);\n' ...
'pkr = zeros(1, max_lab); pkc = zeros(1, max_lab);\n' ...
'for i = 1:n_ifft\n' ...
'    for j = 1:n_pos\n' ...
'        lab = L(i, j);\n' ...
'        if lab <= 0, continue; end\n' ...
'        r = uf_find(lab, parent);\n' ...
'        L(i, j) = r;\n' ...
'        cnt(r) = cnt(r) + 1;\n' ...
'        if img(i, j) > pk(r)\n' ...
'            pk(r) = img(i, j); pkr(r) = i; pkc(r) = j;\n' ...
'        end\n' ...
'    end\n' ...
'end\n' ...
'nclust = 0; sum_d = 0; sum_x = 0; d_min = 0; d_max = 0;\n' ...
'for r = 1:max_lab\n' ...
'    if cnt(r) <= 0, continue; end\n' ...
'    nclust = nclust + 1;\n' ...
'    d = (pkr(r) - 1)*dr;\n' ...
'    xx = (pkc(r) - 1)*dx;\n' ...
'    sum_d = sum_d + d; sum_x = sum_x + xx;\n' ...
'    if nclust == 1, d_min = d; d_max = d; end\n' ...
'    if d < d_min, d_min = d; end\n' ...
'    if d > d_max, d_max = d; end\n' ...
'end\n' ...
'mean_d = 0; mean_x = 0;\n' ...
'if nclust > 0\n' ...
'    mean_d = sum_d/nclust; mean_x = sum_x/nclust;\n' ...
'end\n' ...
'rep = zeros(6, 1);\n' ...
'rep(1) = sum(hits(:));\n' ...
'rep(2) = nclust;\n' ...
'rep(3) = mean_d;\n' ...
'rep(4) = mean_x;\n' ...
'rep(5) = d_min;\n' ...
'rep(6) = d_max;\n' ...
'end\n' ...
'\n' ...
'function root = uf_find(a, parent)\n' ...
'root = a;\n' ...
'guard = 0;\n' ...
'while root > 0 && parent(root) > 0 && parent(root) ~= root && guard < 10000\n' ...
'    root = parent(root);\n' ...
'    guard = guard + 1;\n' ...
'end\n' ...
'end\n' ...
'\n' ...
'function [merged, parent] = uf_union(a, b, parent)\n' ...
'%% Merge labels a and b (a may be 0) and return the surviving root.\n' ...
'if a <= 0\n' ...
'    merged = uf_find(b, parent);\n' ...
'    return;\n' ...
'end\n' ...
'ra = uf_find(a, parent); rb = uf_find(b, parent);\n' ...
'if ra == rb\n' ...
'    merged = ra;\n' ...
'    return;\n' ...
'end\n' ...
'if ra < rb\n' ...
'    parent(rb) = ra; merged = ra;\n' ...
'else\n' ...
'    parent(ra) = rb; merged = rb;\n' ...
'end\n' ...
'end\n'], n_ifft, n_pos, n_freq, max_lab);
end
