function code = code_adc(cfg)
% CODE_ADC  Script for block B07_ADC.
%
%   Ideal sampling plus ENOB-limited quantisation noise. The converter is
%   assumed to be auto-ranged to the incoming peak (a real GPR receiver does
%   this with its attenuator/AGC stage), so the quantisation step is derived
%   from the mean received power of each trace.
%
%   Ports: (rf_in, enob, n_thermal) -> [iq, noise_std]
%       iq         [n_tones x n_positions] complex, noiseless at this point
%       noise_std  [n_positions x 1] per-quadrature standard deviation
%                  (quantisation + thermal), for one single sweep
%
%   The noise itself is added in B08_Averaging so that the sqrt(N) integration
%   gain is applied to the total noise, not only to part of it.

n_freq  = cfg.n_tones;
n_pos   = cfg.n_positions;
enob_min = gpr_cfg_value(cfg, 'adc_enob_min', 8);

code = sprintf([...
'function [iq, noise_std] = fcn(rf_in, enob, n_thermal)\n' ...
'%%#codegen\n' ...
'%% B07_ADC: quantisation noise level of an auto-ranged ENOB-bit converter.\n' ...
'n_freq = %d; n_pos = %d;\n' ...
'if enob < %g, enob = %g; end\n' ...
'snr_q = 10^(6.02*enob/10);      %% signal-to-quantisation-noise power ratio\n' ...
'iq = rf_in;\n' ...
'pw = abs(rf_in).^2;             %% instantaneous power per tone\n' ...
'p_mean = sum(pw, 1)/n_freq;     %% 1 x n_pos\n' ...
'q_var = p_mean/snr_q/2;         %% per quadrature component\n' ...
'noise_std = sqrt(q_var + n_thermal^2);\n' ...
'noise_std = noise_std(:);\n' ...
'end\n'], n_freq, n_pos, enob_min, enob_min);
end
