function code = code_calibration(cfg)
% CODE_CALIBRATION  Script for block B09_Calibration.
%
%   Divides out the known system transfer function: cable delay plus the
%   measured passband ripple. A real system gets these from a factory
%   calibration through a known reference; here they are modelled.
%
%   Ports: (raw, f_start, f_stop) -> cal [n_tones x n_positions]

n_freq       = cfg.n_tones;
n_pos        = cfg.n_positions;
cable_delay  = gpr_cfg_value(cfg, 'rx_cable_delay', 5e-9);
ripple_depth = gpr_cfg_value(cfg, 'cal_ripple_depth', 0.05);
ripple_cycles= gpr_cfg_value(cfg, 'cal_ripple_cycles', 3);

code = sprintf([...
'function cal = fcn(raw, f_start, f_stop)\n' ...
'%%#codegen\n' ...
'%% B09_Calibration: remove the system response (cable delay + passband ripple).\n' ...
'n_freq = %d; n_pos = %d;\n' ...
'cable_delay = %g;\n' ...
'ripple_depth = %g;\n' ...
'ripple_cycles = %g;\n' ...
'bw = f_stop - f_start;\n' ...
'if bw <= 0, bw = 1; end\n' ...
'if n_freq < 2, df = 0; else, df = bw/(n_freq-1); end\n' ...
'cal = complex(zeros(n_freq, n_pos), zeros(n_freq, n_pos));\n' ...
'for k = 1:n_freq\n' ...
'    fk = f_start + (k-1)*df;\n' ...
'    H_sys = exp(-1j*2*pi*fk*cable_delay) ...\n' ...
'          * (1 + ripple_depth*sin(2*pi*(fk - f_start)/bw*ripple_cycles));\n' ...
'    if abs(H_sys) < 1e-9, H_sys = 1e-9; end          %% never divide by ~0\n' ...
'    cal(k, :) = raw(k, :)/H_sys;\n' ...
'end\n' ...
'end\n'], n_freq, n_pos, cable_delay, ripple_depth, ripple_cycles);
end
