function code = code_waveform(cfg)
% CODE_WAVEFORM  Script for block B02_Waveform.
%
%   Stepped-frequency continuous-wave (SFCW) transmit spectrum: one complex
%   tone per frequency step, with an optional raised-cosine edge taper that
%   trades range resolution for lower IFFT sidelobes. Default taper is 0
%   because B10_RangeProc already applies a Kaiser window.
%
%   Ports: (f_start, f_stop) -> tx [n_tones x 1]

n_freq = cfg.n_tones;
taper  = gpr_cfg_value(cfg, 'tx_taper_percent', 0);

code = sprintf([...
'function tx = fcn(f_start, f_stop)\n' ...
'%%#codegen\n' ...
'%% B02_Waveform: SFCW tone comb.\n' ...
'n_freq = %d;\n' ...
'taper_pct = %g;\n' ...
'assert(f_stop > f_start, ''f_stop must be larger than f_start'');\n' ...
'amp = ones(n_freq, 1);\n' ...
'if taper_pct > 0\n' ...
'    nt = round(n_freq*taper_pct/100);\n' ...
'    if nt < 1, nt = 1; end\n' ...
'    if nt > floor(n_freq/2), nt = floor(n_freq/2); end\n' ...
'    for k = 1:nt\n' ...
'        w = 0.5*(1 - cos(pi*(k-0.5)/nt));\n' ...
'        amp(k) = w;\n' ...
'        amp(n_freq-k+1) = w;\n' ...
'    end\n' ...
'end\n' ...
'tx = complex(amp, zeros(n_freq, 1));\n' ...
'end\n'], n_freq, taper);
end
