function code = code_environment(cfg)
% CODE_ENVIRONMENT  Script for block B01_Environment.
%
%   Builds the survey geometry: for each of the n_positions antenna
%   positions the cross-range coordinate x, the along-track coordinate y
%   (always 0 for a 2-D profile) and the standoff height above ground.
%
%   Ports: (altitude, scan_length) -> env_out [3 x n_positions]

n_pos = cfg.n_positions;

code = sprintf([...
'function env_out = fcn(altitude, scan_length)\n' ...
'%%#codegen\n' ...
'%% B01_Environment: survey geometry along the scan line.\n' ...
'n_pos = %d;\n' ...
'if n_pos < 2\n' ...
'    n_pos = 2;\n' ...
'end\n' ...
'env_out = zeros(3, n_pos);\n' ...
'for k = 1:n_pos\n' ...
'    frac = (k-1)/(n_pos-1);\n' ...
'    env_out(1, k) = frac * scan_length;   %% cross-range x, m\n' ...
'    env_out(2, k) = 0;                    %% along-track y, m (2-D profile)\n' ...
'    env_out(3, k) = altitude;             %% standoff above ground, m\n' ...
'end\n' ...
'end\n'], n_pos);
end
