function src = code_rangeproc(cfg)
%CODE_RANGEPROC  Generator for the Range Processing block (B10).
%
%   Inputs : u    - calibrated complex spectrum, n_tones x n_positions (B09)
%            beta - Kaiser beta from the P_KAISER constant port (used only
%                   when cfg.range_window is 'kaiser')
%   Output : rp   - range profiles, n_ifft x n_positions complex
%
%   Range compression is a zero-padded IFFT along the frequency axis of the
%   tapered spectrum.  The taper is cfg.range_window (gpr_range_window): an
%   untapered spectrum has -13 dB range sidelobes whose skirt the migration
%   sums coherently over its aperture, inflating the CFAR noise estimate
%   around weak deep targets until they disappear.
%   The amplitude is normalised by sum(w) so a tone of amplitude A produces a
%   peak of A whatever the window, keeping B09's calibration meaningful.

  wname = lower(gpr_cfg_value(cfg, 'range_window', 'kaiser'));
  if strcmp(wname,'none'), wname = 'rectangular'; end
  names = {'rectangular','hann','hamming','blackman','bartlett','kaiser'};
  if ~any(strcmp(wname, names))
    error('GPR:RangeWindow', ...
      'cfg.range_window ''%s'' is not supported (use one of: %s).', ...
      gpr_cfg_value(cfg,'range_window','kaiser'), strjoin(names, ', '));
  end

  src = sprintf([...
    'function rp = fcn(u, beta)\n' ...
    '%%#codegen\n' ...
    '%% Range compression: windowed, zero-padded IFFT along the frequency axis.\n' ...
    '%% Window: ''%s'' - sidelobe control, see gpr_range_window.m.\n' ...
    'persistent wspec wbeta wgain;\n' ...
    'if isempty(wspec) || abs(wbeta - beta) > 1e-12\n' ...
    '    wspec = gpr_range_window(''%s'', %d, beta).'';\n' ...
    '    wbeta = beta;\n' ...
    '    wgain = %d / sum(wspec);\n' ...
    'end\n' ...
    'x = complex(real(u), imag(u)) .* wspec;\n' ...
    'rp = ifft(x, %d, 1) * wgain;\n' ...
    'end\n'], wname, wname, cfg.n_tones, cfg.n_ifft, cfg.n_ifft);
end
