function src = code_migration(cfg)
%CODE_MIGRATION  Generator for the Kirchhoff Migration block (B12).
%
%   Ports: (bs, f_start, f_stop, moisture, sigma, depth_max, scan_len, alt)
%          -> mig [n_ifft x n_positions] real, >= 0
%
%   Physics
%   -------
%   Each image point (z, x) collects the samples lying on its diffraction
%   hyperbola R = sqrt(z^2 + (x - x_t)^2) from the traces x_t inside the
%   migration aperture and adds them with the matched phase.
%
%   cfg.migration_coherent (default true) selects
%     true  : complex stack with phase exp(+j*2*beta*R), beta at f_start.
%             For absolute tone frequencies f_k = f_start + k*df the IFFT
%             peak of a target at delay tau carries phase -2*pi*f_start*tau,
%             so exp(+j*2*beta_start*R) is the matched phase.  Coherent
%             stacking is what makes the hyperbola arms cancel; an envelope
%             stack cannot cancel and smears a deep target over the section.
%     false : envelope stack of abs(bs) (legacy, only usable when the
%             surface bounce dominates the section).
%
%   Aperture limits - the smallest of the three wins:
%     1. cfg.migration_aperture * z   (user configured fraction of depth)
%     2. the antenna footprint at depth z - beyond it the target is not
%        illuminated, so extra traces only add noise and clutter
%     3. two sampling limits set by the trace spacing dx:
%        (a) operator aliasing - the migration phase varies as
%            2*beta*sin(theta) per metre of trace, so adjacent traces stay
%            within pi/2 rad only for sin(theta) <= lambda_start/(8*dx);
%        (b) output sampling - the focused spot is lambda_c*z/(2*L) wide
%            with L = 2*z*tan(theta); if that is narrower than dx the image
%            grid cannot represent it and every target breaks up into a
%            2-trace ripple of alternating maxima.  This needs
%            tan(theta) <= lambda_c/(4*dx) and is the binding limit for
%            high-frequency shallow surveys.
%   A raised-cosine aperture taper damps the edge traces, where the phase
%   rate is highest.
%
%   Soil properties come from the shared soil_permittivity model using the
%   f_start/f_stop/moisture/sigma constant ports, so the migrated depth axis
%   always agrees with the channel model (B04) and with the detector (B13).

  n_ifft   = cfg.n_ifft;
  n_pos    = cfg.n_positions;
  n_freq   = cfg.n_tones;
  ap_frac  = cfg.migration_aperture;
  tan_beam = cfg.beam_half_angle_tan;
  fp_min   = cfg.footprint_min;
  coherent = gpr_cfg_value(cfg, 'migration_coherent', true);

  if coherent, dat = 'bs'; else, dat = 'abs(bs)'; end

  src = sprintf([...
    'function mig = fcn(bs, f_start, f_stop, moisture, sigma, depth_max, scan_len, alt)\n' ...
    '%%#codegen\n' ...
    '%% B12_Migration: coherent Kirchhoff migration of the background-subtracted\n' ...
    '%% range profiles.  Aperture = min(%g*z, footprint, trace-sampling limit).\n' ...
    'n_ifft = %d; n_pos = %d; n_freq = %d;\n' ...
    'ap_frac = %g; tan_beam = %g; fp_min = %g; coherent = %d;\n' ...
    'c0 = 299792458;\n' ...
    'if f_start <= 0, f_start = 1e6; end\n' ...
    'if f_stop <= f_start, f_stop = f_start + 1e6; end\n' ...
    'if moisture < 0, moisture = 0; end\n' ...
    'if sigma <= 0, sigma = 1e-4; end\n' ...
    '[~, ~, alpha, ~, v] = soil_permittivity((f_start + f_stop)/2, moisture, sigma);\n' ...
    'if n_freq < 2, df = 1; else, df = (f_stop - f_start)/(n_freq - 1); end\n' ...
    'if df <= 0, df = 1; end\n' ...
    'dr = v/(2*n_ifft*df);\n' ...
    'if dr <= 0, dr = 1; end\n' ...
    'beta0 = 2*pi*f_start/v;          %% phase constant at f_start [rad/m]\n' ...
    'lambda0 = v/f_start;             %% wavelength at f_start (phase reference)\n' ...
    'lambda_c = v/((f_start + f_stop)/2);   %% wavelength at f_center (resolution)\n' ...
    'if n_pos < 2, dx = 1; else, dx = scan_len/(n_pos - 1); end\n' ...
    'if dx <= 0, dx = 1; end\n' ...
    '%% trace-sampling limits: (a) inter-trace phase step < pi/2,\n' ...
    '%% (b) focused spot no narrower than the trace spacing\n' ...
    'sin_max = min(0.95, lambda0/(8*dx));\n' ...
    'tan_alias = sin_max/sqrt(max(1e-6, 1 - sin_max*sin_max));\n' ...
    'tan_spot = lambda_c/(4*dx);\n' ...
    'tan_lim = min(tan_alias, tan_spot);\n' ...
    'r_off = alt*(v/c0);              %% air leg expressed as soil depth [m]\n' ...
    'max_bin = min(n_ifft, floor(depth_max/dr) + 2);\n' ...
    'if max_bin < 2, max_bin = 2; end\n' ...
    'dat = %s;\n' ...
    'mig = zeros(n_ifft, n_pos);\n' ...
    'for iz = 1:max_bin\n' ...
    '    z = (iz - 1)*dr;\n' ...
    '    if z <= 0, continue; end\n' ...
    '    ap = min([ap_frac*z, max((alt + z)*tan_beam, fp_min), tan_lim*z]);\n' ...
    '    nap = max(1, floor(ap/dx));\n' ...
    '    for ix = 1:n_pos\n' ...
    '        acc = complex(0); nc = 0;   %% complex from the first assignment\n' ...
    '        for s = -nap:nap\n' ...
    '            it = ix + s;\n' ...
    '            if it < 1 || it > n_pos, continue; end\n' ...
    '            xs = s*dx;\n' ...
    '            R = sqrt(z*z + xs*xs);\n' ...
    '            fb = 1 + (R + r_off)/dr;      %% two-way travel bin + air leg\n' ...
    '            b0 = floor(fb); fr = fb - b0;\n' ...
    '            if b0 < 1 || b0 + 1 > n_ifft, continue; end\n' ...
    '            val = (1 - fr)*dat(b0, it) + fr*dat(b0 + 1, it);\n' ...
    '            %% obliquity, spreading and attenuation compensation\n' ...
    '            w = (z/R)/sqrt(R)*exp(-2*alpha*(R - z));\n' ...
    '            %% raised-cosine aperture taper\n' ...
    '            w = w*0.5*(1 + cos(pi*s/(nap + 1)));\n' ...
    '            if coherent\n' ...
    '                acc = acc + w*val*exp(1j*2*beta0*R);\n' ...
    '            else\n' ...
    '                acc = acc + w*val;\n' ...
    '            end\n' ...
    '            nc = nc + 1;\n' ...
    '        end\n' ...
    '        if nc > 0, mig(iz, ix) = abs(acc)/sqrt(nc); end\n' ...
    '    end\n' ...
    'end\n' ...
    'end\n'], ap_frac, n_ifft, n_pos, n_freq, ap_frac, tan_beam, fp_min, ...
    coherent, dat);
end
