function code = code_channel(cfg)
% CODE_CHANNEL  Script for block B04_Channel.
%
%   Two-way propagation model:
%     * specular air/soil bounce (the surface clutter every GPR A-scan has),
%     * one diffraction tail per buried target, using the radar equation with
%       the slant path in soil, conductivity attenuation and a beam-footprint
%       weighting.
%
%   Ports: (env_in, tx_in, moisture, sigma, tgt_d, tgt_x, tgt_rcs,
%           f_start, f_stop) -> ch_out [n_tones x n_positions]
%
%   Non-dispersive soil (important)
%   -------------------------------
%   eps_r and alpha are evaluated ONCE, at the band centre, through the same
%   soil_permittivity model that B12_Migration, B13_Detection, B14_Report and
%   the feasibility check use.  beta(f) = 2*pi*f/v is therefore linear in f,
%   i.e. a target is a pure delay, which is exactly what the range
%   compression and the Kirchhoff migration invert.
%
%   The Dobson model is dispersive: over the 0.5-3 GHz mode-A band eps_r falls
%   by ~15%, which makes the phase non-linear in f, smears the compressed
%   pulse and - because the error grows with range - defocuses the migration
%   into a ripple of alternating maxima.  Treating the soil as a low-loss
%   dielectric with a single phase velocity is the standard GPR forward-model
%   assumption (gprMax, ReflexW) and keeps the digital twin invertible.  Only
%   lambda = c/f in the spreading term is left frequency dependent, which is
%   an amplitude effect and does not disturb the phase.
%
%   Other corrections with respect to the previous version:
%     * the soil path is the SLANT range sqrt(depth^2 + offset^2), so the data
%       really contains hyperbolic moveout for B12 to focus;
%     * the beam footprint grows with depth, (standoff + depth)*tan(half beam);
%     * the surface bounce is the Fresnel coefficient of a plane interface
%       (which fills the beam) instead of a point-target 1/R^2 term that blew
%       up for a 2 cm ground clearance;
%     * the absolute field scale comes from EIRP only, so it cannot be applied
%       twice together with the TX chain output.

n_freq    = cfg.n_tones;
n_pos     = cfg.n_positions;
n_targets = cfg.n_targets;
eirp      = cfg.eirp_dBm;
tan_ha    = gpr_cfg_value(cfg, 'beam_half_angle_tan', tan(pi/6));
fp_min    = gpr_cfg_value(cfg, 'footprint_min', 0.30);

code = sprintf([...
'function ch_out = fcn(env_in, tx_in, moisture, sigma, tgt_d, tgt_x, tgt_rcs, f_start, f_stop)\n' ...
'%%#codegen\n' ...
'%% B04_Channel: surface bounce + buried-target diffraction tails.\n' ...
'%% Soil properties come from soil_permittivity at the band centre, the same\n' ...
'%% single phase velocity that B12_Migration and B13_Detection assume.\n' ...
'n_freq = %d; n_pos = %d; n_targets = %d;\n' ...
'c = 299792458;\n' ...
'eirp_dBm = %g;\n' ...
'tan_ha = %g;\n' ...
'fp_min = %g;\n' ...
'p_tx = 10^(eirp_dBm/10)/1000;      %% radiated power, W\n' ...
'amp_tx = sqrt(p_tx);               %% field reference into 1 ohm\n' ...
'if f_start <= 0, f_start = 1e6; end\n' ...
'if f_stop <= f_start, f_stop = f_start + 1e6; end\n' ...
'if moisture < 0, moisture = 0; end\n' ...
'if sigma <= 0, sigma = 1e-4; end\n' ...
'f_c = (f_start + f_stop)/2;\n' ...
'[eps_r, ~, alpha, ~, v] = soil_permittivity(f_c, moisture, sigma);\n' ...
'n2 = sqrt(eps_r);\n' ...
'Gamma = (n2 - 1)/(n2 + 1);         %% air/soil reflection coefficient\n' ...
'T2 = (1 - Gamma^2)^2;              %% two-way interface transmission\n' ...
'if n_freq < 2, df = 1; else, df = (f_stop - f_start)/(n_freq - 1); end\n' ...
'x_vec = env_in(1, :);\n' ...
'z_vec = env_in(3, :);\n' ...
'R_air = max(z_vec, 0.01);\n' ...
'ch_out = complex(zeros(n_freq, n_pos), zeros(n_freq, n_pos));\n' ...
'for k = 1:n_freq\n' ...
'    f = f_start + (k-1)*df;\n' ...
'    lambda = c/f; k_air = 2*pi*f/c; beta = 2*pi*f/v;\n' ...
'    H = Gamma*exp(-1j*2*k_air*R_air);   %% plane interface fills the beam\n' ...
'    for t = 1:n_targets\n' ...
'        d = tgt_d(t);\n' ...
'        rh = abs(x_vec - tgt_x(t));\n' ...
'        R_s = sqrt(d*d + rh.*rh);       %% slant path in soil\n' ...
'        R_eff = R_air + R_s;            %% total one-way path\n' ...
'        fp = max((z_vec + d)*tan_ha, fp_min);   %% illuminated footprint radius\n' ...
'        bw = exp(-2*(rh./fp).^2);\n' ...
'        atten = exp(-2*alpha*R_s);      %% two-way soil attenuation\n' ...
'        spread = lambda./((4*pi)^1.5*R_eff.^2);\n' ...
'        contrib = sqrt(max(tgt_rcs(t), 0))*T2*atten.*spread.*bw ...\n' ...
'            .*exp(-1j*2*(k_air*R_air + beta*R_s));\n' ...
'        contrib = contrib.*(bw >= 1e-3);        %% outside the beam: ignore\n' ...
'        H = H + contrib;\n' ...
'    end\n' ...
'    ch_out(k, :) = H*amp_tx*tx_in(k);\n' ...
'end\n' ...
'end\n'], n_freq, n_pos, n_targets, eirp, tan_ha, fp_min);
end
