function code = code_coupling(cfg)
% CODE_COUPLING  Script for block B05_Coupling.
%
%   Direct TX->RX antenna leakage, added to the channel response. The leakage
%   travels the antenna separation in air, so it carries the phase delay
%   exp(-j*2*pi*f*sep/c) and therefore lands in the first range bins of the
%   A-scan - exactly what a real GPR trace shows. The isolation value
%   (cfg.antenna_coupling_dB, negative) already includes the free-space
%   spreading between the two antennas.
%
%   Ports: (tx_in, coupling_dB, ch_in) -> y [n_tones x n_positions]

n_freq = cfg.n_tones;
n_pos  = cfg.n_positions;
sep    = cfg.tx_rx_separation;
f0     = cfg.f_start;
f1     = cfg.f_stop;
eirp   = cfg.eirp_dBm;

code = sprintf([...
'function y = fcn(tx_in, coupling_dB, ch_in)\n' ...
'%%#codegen\n' ...
'%% B05_Coupling: direct TX-RX leakage on top of the channel response.\n' ...
'n_freq = %d; n_pos = %d;\n' ...
'c = 299792458;\n' ...
'separation = %g;\n' ...
'f_start = %g; f_stop = %g;\n' ...
'amp_tx = sqrt(10^(%g/10)/1000);\n' ...
'if separation < 0, separation = 0; end\n' ...
'if n_freq < 2, df = 1; else, df = (f_stop - f_start)/(n_freq-1); end\n' ...
'coupling_lin = 10^(coupling_dB/20);\n' ...
'tau = separation/c;                %% one-way air delay between the antennas\n' ...
'y = ch_in;\n' ...
'for k = 1:n_freq\n' ...
'    f = f_start + (k-1)*df;\n' ...
'    leak = coupling_lin*amp_tx*tx_in(k)*exp(-1j*2*pi*f*tau);\n' ...
'    y(k, :) = y(k, :) + leak;\n' ...
'end\n' ...
'end\n'], n_freq, n_pos, sep, f0, f1, eirp);
end
