function code = code_detection(cfg)
% CODE_DETECTION  Script for block B13_Detection.
%
%   Two-dimensional CFAR over the migrated image.  For every cell under test
%   the surrounding noise level is estimated from the training cells - a
%   (2w+1)x(2w+1) window minus a (2g+1)x(2g+1) guard window, w = guard+train
%   - and the cell is declared a detection when its power exceeds
%   alpha * level.
%
%   Two estimators (cfg.cfar_estimator):
%
%   'log'  (default) robust log-domain / geometric-mean CFAR.
%          level = exp( mean(log p) + gamma ),  gamma = Euler's constant,
%          which is unbiased for exponentially distributed power, and
%          alpha = log(1/Pfa)  (exact in the large-N limit).
%          Why it is the default: in a scene with several targets the
%          training window of a deep, weak target always contains the bright
%          blob of a shallower neighbour.  An arithmetic mean then reports
%          that neighbour as "noise" - measured on the mode-B reference
%          scene the mean level next to the 15 m target was 1e11 times the
%          true noise floor, which masks the target completely.  The
%          geometric mean is set by the typical (noise) cell and barely
%          moves when a few bright cells enter the window.
%
%   'mean' classical CA-CFAR: level = mean(p) over the training cells and
%          the exact multiplier alpha = N*(Pfa^(-1/N) - 1).  Kept because it
%          is the textbook reference; use it for single-target scenes.
%
%   Window sums are computed with separable convolutions instead of a
%   4-deep nested loop (orders of magnitude faster, identical results).
%   Cells outside the surveyed depth band [d_min, d_max] are excluded from
%   both the sums and the counts: B12 does not migrate there, so they are
%   identically zero and would otherwise halve the estimated noise level and
%   raise a wall of false alarms along the band edge.
%
%   Ports: (mig, d_min, d_max, pfa, f_start, f_stop, moisture, sigma)
%          -> det [n_ifft x n_positions] double, 1 = detection

n_ifft  = cfg.n_ifft;
n_pos   = cfg.n_positions;
n_freq  = cfg.n_tones;
guard   = gpr_cfg_value(cfg, 'cfar_guard', 4);
train   = gpr_cfg_value(cfg, 'cfar_train', 8);
est     = lower(gpr_cfg_value(cfg, 'cfar_estimator', 'log'));
if ~any(strcmp(est, {'log','mean'}))
    error('GPR:CfarEstimator', 'cfar_estimator must be ''log'' or ''mean'' (got ''%s'').', ...
        gpr_cfg_value(cfg, 'cfar_estimator', 'log'));
end
robust = strcmp(est, 'log');

code = sprintf([...
'function det = fcn(mig, d_min, d_max, pfa, f_start, f_stop, moisture, sigma)\n' ...
'%%#codegen\n' ...
'%% B13_Detection: 2-D CFAR on the migrated image (estimator: %s).\n' ...
'n_ifft = %d; n_pos = %d; n_freq = %d;\n' ...
'guard = %d; train = %d; robust = %d;\n' ...
'c = 299792458;\n' ...
'if f_start <= 0, f_start = 1e6; end\n' ...
'if f_stop <= f_start, f_stop = f_start + 1e6; end\n' ...
'if moisture < 0, moisture = 0; end\n' ...
'if sigma <= 0, sigma = 1e-4; end\n' ...
'[~, ~, ~, ~, v_soil] = soil_permittivity((f_start + f_stop)/2, moisture, sigma);\n' ...
'if n_freq < 2, df = 1; else, df = (f_stop - f_start)/(n_freq - 1); end\n' ...
'if df <= 0, df = 1; end\n' ...
'dr = v_soil/(2*n_ifft*df);\n' ...
'if dr <= 0, dr = 1; end\n' ...
'b_min = floor(d_min/dr) + 1;\n' ...
'b_max = floor(d_max/dr) + 1;\n' ...
'if b_min < 1, b_min = 1; end\n' ...
'if b_max > n_ifft, b_max = n_ifft; end\n' ...
'if b_max < b_min, b_max = b_min; end\n' ...
'if pfa <= 0, pfa = 1e-6; end\n' ...
'if pfa >= 1, pfa = 0.5; end\n' ...
'w = guard + train;\n' ...
'valid = zeros(n_ifft, n_pos);\n' ...
'valid(b_min:b_max, :) = 1;\n' ...
'pm_raw = mig.^2;\n' ...
'%% floor keeps log() finite in dead pixels without affecting any threshold\n' ...
'p_floor = max(pm_raw(:))*1e-14;\n' ...
'if ~(p_floor > 0), p_floor = 1e-30; end\n' ...
'pmf = max(pm_raw, p_floor);\n' ...
'pmap = pmf .* valid;\n' ...
'kb = ones(2*w+1, 1); kr = ones(1, 2*w+1);\n' ...
'kg = ones(2*guard+1, 1); kgr = ones(1, 2*guard+1);\n' ...
'big_cnt = conv2(conv2(valid, kb, ''same''), kr, ''same'');\n' ...
'g_cnt = conv2(conv2(valid, kg, ''same''), kgr, ''same'');\n' ...
'noise_cnt = big_cnt - g_cnt;\n' ...
'noise_cnt(noise_cnt < 1) = 1;\n' ...
'n_ref = (2*w+1)^2 - (2*guard+1)^2;\n' ...
'if robust\n' ...
'    lmap = log(pmf) .* valid;\n' ...
'    l_big = conv2(conv2(lmap, kb, ''same''), kr, ''same'');\n' ...
'    l_g = conv2(conv2(lmap, kg, ''same''), kgr, ''same'');\n' ...
'    %% exp(mean(log p) + gamma) is unbiased for exponential power\n' ...
'    level = exp((l_big - l_g)./noise_cnt + 0.5772156649015329);\n' ...
'    alpha_c = log(1/pfa);\n' ...
'else\n' ...
'    big_sum = conv2(conv2(pmap, kb, ''same''), kr, ''same'');\n' ...
'    g_sum = conv2(conv2(pmap, kg, ''same''), kgr, ''same'');\n' ...
'    level = (big_sum - g_sum)./noise_cnt;\n' ...
'    alpha_c = n_ref*(pfa^(-1/n_ref) - 1);\n' ...
'end\n' ...
'det = double((pmap > alpha_c*level) & (valid > 0) & (noise_cnt > 0));\n' ...
'end\n'], est, n_ifft, n_pos, n_freq, guard, train, robust);
end
