function code = code_background(cfg)
% CODE_BACKGROUND  Script for block B11_Background.
%
%   Removes the position-invariant clutter of a GPR section: the direct TX-RX
%   coupling and the air/soil surface bounce. Both are identical in every
%   trace of a level survey, so they live in a single rank-1 mode whose right
%   singular vector is the uniform vector.
%
%   The estimate is the component-wise MEDIAN across positions, not the mean
%   and not a raw power iteration:
%     * a mean (or any rank-1 mode with a uniform right vector) also contains
%       every strong localised target, and subtracting it smears that target
%       over the whole section. With the mode-B configuration this pedestal
%       was ~9% of the target amplitude at every trace, which raised the CFAR
%       noise estimate enough to suppress all detections.
%     * the median ignores the traces that actually see a target (a minority
%       of the section), so the background estimate stays clean.
%   Modes 2..n_remove still use power-iteration deflation for users who want
%   to remove additional, non-uniform clutter; they are off by default
%   because they can eat target energy.
%
%   Ports: (rp, n_remove) -> bs [n_ifft x n_positions] complex

n_ifft = cfg.n_ifft;
n_pos  = cfg.n_positions;

code = sprintf([...
'function bs = fcn(rp, n_remove)\n' ...
'%%#codegen\n' ...
'%% B11_Background: remove position-invariant clutter (coupling + surface).\n' ...
'n_ifft = %d; n_pos = %d;\n' ...
'm_max = floor(n_remove);\n' ...
'if m_max < 0, m_max = 0; end\n' ...
'if m_max > 5, m_max = 5; end\n' ...
'A = complex(rp);   %% complex from the first assignment\n' ...
'if m_max >= 1\n' ...
'    %% robust background trace: component-wise median across positions\n' ...
'    bg = median(real(A), 2) + 1i*median(imag(A), 2);\n' ...
'    A = A - repmat(bg, 1, n_pos);\n' ...
'end\n' ...
'for m = 2:m_max\n' ...
'    %% optional extra rank-1 deflation by power iteration\n' ...
'    v = complex(ones(n_pos,1)/sqrt(n_pos), zeros(n_pos,1));\n' ...
'    u = A*v;\n' ...
'    for it = 1:30\n' ...
'        un = norm(u);\n' ...
'        if un < 1e-12, break; end\n' ...
'        u = u/un;\n' ...
'        v = A''*u;\n' ...
'        vn = norm(v);\n' ...
'        if vn < 1e-12, break; end\n' ...
'        v = v/vn;\n' ...
'        u = A*v;\n' ...
'    end\n' ...
'    sigma = norm(u);\n' ...
'    if sigma < 1e-12, break; end\n' ...
'    u = u/sigma;\n' ...
'    A = A - sigma*(u*v'');\n' ...
'end\n' ...
'bs = A;\n' ...
'end\n'], n_ifft, n_pos);
end
